{
 "title": "ZFS Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "viewingPool",
    "label": "ZFS Pool",
    "query": {
     "query": "label_values(zfs_health{device_type=\"pool\"}, pool)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Pool Space Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "zfs_capacity{device_name=\"$viewingPool\"} - zfs_available{device_name=\"$viewingPool\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pool Space Usage",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(zfs_capacity{device_name=\"$viewingPool\"} - zfs_available{device_name=\"$viewingPool\"}) / zfs_capacity{device_name=\"$viewingPool\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pool Fragmentation",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "zfs_fragmentation{pool=\"$viewingPool\", device_type=\"pool\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pool Total Errors",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(zfs_checksum_errors{device_name=\"$viewingPool\", device_type=\"pool\"}) + sum(zfs_write_errors{device_name=\"$viewingPool\", device_type=\"pool\"}) + sum(zfs_read_errors{device_type=\"pool\",device_name=~\"$viewingPool\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pool Health",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(zfs_health{pool=\"$viewingPool\", device_name=\"$viewingPool\", state=\"online\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pool Read Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "zfs_read_bandwidth{device_type=\"pool\", device_name=\"$viewingPool\"}",
     "legendFormat": "{{device_name}}"
    }
   ]
  },
  {
   "title": "Pool Write Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "zfs_write_bandwidth{device_type=\"pool\", device_name=\"$viewingPool\"}",
     "legendFormat": "{{device_name}}"
    }
   ]
  },
  {
   "title": "Disk Status",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "zfs_health{device_type=\"disk\", pool=\"$viewingPool\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Read Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "zfs_read_bandwidth{pool=\"$viewingPool\", device_type=\"disk\"}",
     "legendFormat": "{{device_name}}"
    }
   ]
  },
  {
   "title": "Disk Write Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "zfs_write_bandwidth{pool=\"$viewingPool\", device_type=\"disk\"}",
     "legendFormat": "{{device_name}}"
    }
   ]
  },
  {
   "title": "Per drive read errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "zfs_read_errors{device_type=\"disk\", pool=\"$viewingPool\"}",
     "legendFormat": "{{device_name}}"
    }
   ]
  },
  {
   "title": "Per drive write errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 14 },
   "targets": [
    {
     "expr": "zfs_write_errors{device_type=\"disk\", pool=\"$viewingPool\"}",
     "legendFormat": "{{device_name}}"
    }
   ]
  },
  {
   "title": "Per drive check sum errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 14 },
   "targets": [
    {
     "expr": "zfs_checksum_errors{device_type=\"disk\", pool=\"$viewingPool\"}",
     "legendFormat": "{{device_name}}"
    }
   ]
  }
 ]
}